name: BileTools
version: 2.1
main: com.cepi.bile.BileTools
commands: 
  biletools:
    description: Manages biletools
    aliases: [bile]
permissions:
  bile.use: 
    description: Gives access to biletools
    default: op