name: KotTools
version: 2.1
api-version: 1.15
main: world.cepi.kotlintools.KotlinTools
commands:
  kotlintools:
    description: Manages kotlintools
    aliases: [kotlin]
permissions:
  kotlin.use:
    description: Gives access to kotlintools
    default: op