name: BileTools
version: 2.1
api-version: 1.15
main: world.cepi.kotlintools.KotlinTools
commands: 
  biletools:
    description: Manages biletools
    aliases: [bile]
permissions:
  bile.use: 
    description: Gives access to biletools
    default: op